### ISSUE TITLE
howdy/src/lib/shared imports in component/modules are broken

### ISSUE THREAD

**Issue by ashar340** [kreuzerk/howdy#9]
Changed the import as follows for howdy-name.component.ts to make use of the interface:
`import {Component, Input} from '@angular/core';
**import {Foo} from '../shared/';**

@Component({
  selector: 'howdy-name',
  template: `<h1>Hello {{name}}</h1>`
})
export class HowdyNameComponent {
  @Input() name: string;
  something: Foo;
}
`
Getting these errors:
`[error] Error: error TS6059: File '/GitHub/howdy/projects/howdy/src/lib/shared/foo.model.ts' is not under 'rootDir' '\GitHub\howdy\projects\howdy\src\lib\name'. 'rootDir' is expected to contain all source files.

error TS6059: File /GitHub/howdy/projects/howdy/src/lib/shared/index.ts' is not under 'rootDir' \GitHub\howdy\projects\howdy\src\lib\name'. 'rootDir' is expected to contain all source files.

error TS6059: File /GitHub/howdy/projects/howdy/src/lib/shared/public_api.ts' is not under 'rootDir' \GitHub\howdy\projects\howdy\src\lib\name'. 'rootDir' is expected to contain all source files.`

**Comment by nivekcode** [comment]
Hi @ashar340 thx a lot for bringing this up. I also saw the comment on the blogpost. In order to share an interface between multiple subentries you need to add it to a dedicated subentry - for example a shared subentry. 

Check out this response for further details: https://kevinkreuzer.medium.com/hi-bjorn-harvold-1c614dca2e44
